
[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 10, y = 10 }
opacity = 1.0

[general]
import = [ "/home/arope/.config/alacritty/themes/themes/one_dark.toml" ]
